# note: use same title as in readme - otherwise gets duplicated on page
##    see the pages-themes/primer  for details


# note: encoded in html thus   & becomes => &amp; 

title: "Vienna Crypto Programming Meetup / Stammtisch"
